version: '3.8'

services:
  postgres:
    build:
      context: services/postgres
      dockerfile: Dockerfile.development
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=medical
      - POSTGRES_PASSWORD=7059314
    volumes:
      - "db-data:/var/lib/postgresql/data"


  app:
    build:
      context: services/app
      dockerfile: Dockerfile.development
    environment:
      - PORT=8091
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/medical
      - JS_URL=http://localhost
    image: 'medical-application'
    ports:
      - 8091:8091
    depends_on:
      - postgres

  js:
    build:
      context: services/js
      dockerfile: Dockerfile.development
    image: 'my-js-app'
    ports:
      - 80:80

volumes:
  db-data: